/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-06-21 20:11:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bookshop.shopping;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ch14.bookshop.shopping.CartDataBean;
import ch14.bookshop.shopping.CartDBBean;
import ch14.bookshop.shopping.CustomerDataBean;
import ch14.bookshop.shopping.CustomerDBBean;
import ch14.bookshop.shopping.BuyDBBean;
import java.util.List;
import java.text.NumberFormat;

public final class buyForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ch14.bookshop.shopping.CustomerDataBean");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ch14.bookshop.shopping.CartDataBean");
    _jspx_imports_classes.add("ch14.bookshop.shopping.CustomerDBBean");
    _jspx_imports_classes.add("ch14.bookshop.shopping.BuyDBBean");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("ch14.bookshop.shopping.CartDBBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");
	String title = "Book Shopping Mall";
	String book_kind = request.getParameter("book_kind");
	String buyer = (String)session.getAttribute("id");
	
	List<CartDataBean> cartLists = null;
	List<String> accountLists = null;
	CartDataBean cartList = null;
	CustomerDataBean member= null;
	int number = 0;
	int total = 0;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../module/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(title ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");

if(session.getAttribute("id")==null){
	response.sendRedirect("shopMain.jsp");        
}else{
	CartDBBean bookProcess = CartDBBean.getInstance();
    cartLists = bookProcess.getCart(buyer);
    
    CustomerDBBean memberProcess = CustomerDBBean.getInstance();
    member = memberProcess.getMember(buyer);
    
    BuyDBBean buyProcess = BuyDBBean.getInstance();
    accountLists = buyProcess.getAccount();

      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<h3 class=\"pb-3 mb-4 font-italic border-bottom\">구매하기</h3>\r\n");
      out.write("\r\n");
      out.write("\t<form name=\"inform\" method=\"post\" action=\"updateCart.jsp\">\r\n");
      out.write("\t<table class=\"table\"> \r\n");
      out.write("\t<thead class=\"thead-light\"> \r\n");
      out.write("\t  <tr> \r\n");
      out.write("\t    <th>번호</th> \r\n");
      out.write("\t    <th>책이름</th> \r\n");
      out.write("\t    <th>판매가격</th>\r\n");
      out.write("\t    <th>수량</th> \r\n");
      out.write("\t    <th>금액</th>\r\n");
      out.write("\t  </tr>   \r\n");
      out.write("\t</thead>\t\r\n");

  for(int i=0;i<cartLists.size();i++){
     cartList = cartLists.get(i);

      out.write("\r\n");
      out.write("     <tr> \r\n");
      out.write("       <td>");
      out.print(++number );
      out.write("</td> \r\n");
      out.write("       <td>\r\n");
      out.write("         <img src=\"/cban/imageFile/");
      out.print(cartList.getBook_image());
      out.write("\" border=\"0\" width=\"30\" height=\"50\" align=\"middle\">\r\n");
      out.write("           ");
      out.print(cartList.getBook_title());
      out.write("\r\n");
      out.write("       </td> \r\n");
      out.write("       <td>");
      out.print(NumberFormat.getInstance().format(cartList.getBuy_price()));
      out.write("</td>\r\n");
      out.write("       <td>");
      out.print(cartList.getBuy_count());
      out.write("</td> \r\n");
      out.write("       <td>\r\n");
      out.write("          ");
total += cartList.getBuy_count()*cartList.getBuy_price();
      out.write("\r\n");
      out.write("          ");
      out.print(NumberFormat.getInstance().format(cartList.getBuy_count()*cartList.getBuy_price()) );
      out.write("\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");

  }

      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"5\" align=\"right\"><b>총 구매금액 : ");
      out.print(NumberFormat.getInstance().format(total));
      out.write("</b></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
} 
 
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<form method=\"post\" action=\"buyPro.jsp\" name=\"buyinput\">\r\n");
      out.write("<h2>주문자 정보</h2>\r\n");
      out.write("\t<div class=\"form-group row\">\r\n");
      out.write(" \t\t<label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">성명</label>\r\n");
      out.write("\t \t<div class=\"col-sm-10\">\r\n");
      out.write("\t \t\t<input type=\"text\" class=\"form-control\" value=\"");
      out.print(member.getName());
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  \r\n");
      out.write("\t<div class=\"form-group row\">\r\n");
      out.write("\t  \t<label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">전화번호</label>\r\n");
      out.write("\t  \t<div class=\"col-sm-10\">\r\n");
      out.write("\t    \t<input type=\"text\" class=\"form-control\" value=\"");
      out.print(member.getTel());
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"form-group row\">\r\n");
      out.write("\t    <label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">주소</label>\r\n");
      out.write("\t    <div class=\"col-sm-10\">\r\n");
      out.write("\t    \t<input type=\"text\" class=\"form-control\" value=\"");
      out.print(member.getAddress());
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"form-group row\">\r\n");
      out.write("\t    <label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">결제 계좌</label>\r\n");
      out.write("\t    <div class=\"col-sm-10\">\r\n");
      out.write("\t      <select name=\"account\" class=\"form-control\">\r\n");
      out.write("\t\t\t");

				for(int i=0;i<accountLists.size();i++){
				 String accountList = accountLists.get(i);
			
      out.write("\r\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(accountList );
      out.write('"');
      out.write('>');
      out.print(accountList );
      out.write("</option>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t      </select>\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("   \r\n");
      out.write("<h2>배송지 정보</h2>\r\n");
      out.write("\t<div class=\"form-group row\">\r\n");
      out.write("\t    <label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">성명</label>\r\n");
      out.write("\t    <div class=\"col-sm-10\">\r\n");
      out.write("\t    \t<input type=\"text\" class=\"form-control\" name=\"deliveryName\" value=\"");
      out.print(member.getName());
      out.write("\">\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"form-group row\">\r\n");
      out.write("\t   <label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">전화번호</label>\r\n");
      out.write("\t   <div class=\"col-sm-10\">\r\n");
      out.write("\t   \t\t<input type=\"text\" class=\"form-control\" name=\"deliveryTel\" value=\"");
      out.print(member.getTel());
      out.write("\">\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"form-group row\">\r\n");
      out.write("\t   <label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">주소</label>\r\n");
      out.write("\t   <div class=\"col-sm-10\">\r\n");
      out.write("\t   \t\t<input type=\"text\" class=\"form-control\" name=\"deliveryAddress\" value=\"");
      out.print(member.getAddress());
      out.write("\">\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("       <input type=\"submit\" class=\"btn btn-sm btn-outline-primary\" value=\"확인\" >\r\n");
      out.write("       <input type=\"button\" class=\"btn btn-sm btn-outline-secondary\" value=\"취소\" onclick=\"javascript:window.location='shopMain.jsp'\">   \r\n");
      out.write("    </div>   \r\n");
      out.write("  </form>\r\n");
      out.write("</div> <!-- /.container -->\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../module/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
